projects-bff:
  stage: Development

server:
  port: 8081

variables:
  host:
    bff: http://localhost:8081
    api: http://localhost:8080
    spa: http://localhost:3001

spring:
  devtools:
    livereload:
      port: 35730
