name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  APP: bff

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-docker.outputs.version }}
    steps:
      - id: build-docker
        name: Build Docker
        uses: eviive/actions/build/docker@main
        with:
          docker-hub-repository: ${{ vars.DOCKER_HUB_REPOSITORY }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
          docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
          docker-tag-prefix: ${{ vars.DOCKER_TAG_PREFIX }}
          docker-build-args-version: true

  gitops-kustomize-pr:
    name: GitOps Kustomize PR
    needs: build-docker
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: GitOps Kustomize PR
        uses: eviive/actions/gitops/kustomize/pull-request@main
        with:
          repository: ${{ vars.GITOPS_REPOSITORY }}
          token: ${{ secrets.GITOPS_TOKEN }}
          kustomize-working-directory: ${{ env.APP }}/overlays/production
          kustomize-image: ${{ env.APP }}
          docker-image: ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}
          docker-tag: ${{ needs.build-docker.outputs.version }}
