name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  APP: bff

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-docker.outputs.version }}
    steps:
      - id: build-docker
        name: Build Docker
        uses: eviive/actions/build/docker@main
        with:
          docker-hub-repository: ${{ vars.DOCKER_HUB_REPOSITORY }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
          docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
          docker-tag-prefix: ${{ vars.DOCKER_TAG_PREFIX }}
          docker-build-args-version: true

  gitops-pr:
    name: GitOps PR
    needs: build-docker
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.build-docker.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.GITOPS_REPOSITORY }}
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Setup Kustomize
        uses: eviive/actions/install/kustomize@main

      - name: Update image
        working-directory: ${{ env.APP }}/overlays/production
        run: kustomize edit set image ${{ env.APP }}=${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}:${{ env.VERSION }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          commit-message: "ops(${{ env.APP }}): ${{ env.VERSION }}"
          branch: release/${{ env.APP }}/${{ env.VERSION }}
          title: "Release ${{ env.APP }}: ${{ env.VERSION }}"
          body: ""
          assignees: ${{ github.actor }}
