name: Pull Request

on:
  pull_request:

jobs:
  checkstyle:
    name: CheckStyle
    runs-on: ubuntu-latest
    steps:
      - name: CheckStyle
        uses: eviive/actions/validate/lint/checkstyle@main
        with:
          version: 10.26.1
          properties: |
            config_loc=config/checkstyle
